---
- hosts: webservers
  environment:
    - AWS_ACCESS_KEY_ID: "AKIA5BVBOQE6OQLXRP5L"
    - AWS_SECRET_ACCESS_KEY: "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"

  tasks:
  - name: copy env file
    copy:
      src: ~/laravel.pem
      dest: ~/
      mode: '0644'
    become: yes